name: Deploy to GitHub Pages

on:
  push:
    branches: [ source ]  # Your development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants the workflow permission to push to 'main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: source  # Checkout your development branch

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
          cname: nivozer.com
          keep_files: true
