name: Deploy to GitHub Pages
on:
  push:
    branches: [source]  # Trigger the workflow on pushes to the 'source' branch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js version 20
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Build the project
      - run: npm run build


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to the build directory (replace with your actual output directory)
